// ComponentDescriptor.java
// Author  Winston Prakash

package com.nayaware.netinstaller;

import java.awt.event.*;

public class ComponentDescriptor extends javax.swing.JPanel {
    private String name="";
    private String displayName="";
    private String description="";
    private boolean active=true;
    
    private String installerName = "";
    
    private ComponentDescriptor requiredComponent = null;
    private ComponentDescriptor requiredByComponent = null;
    
    private boolean required = false;
    
    /** Creates new form ComponentDescriptor */
    public ComponentDescriptor() {
        initComponents();
        iconLabel.setIcon(new CreateIcon(CreateIcon.TickMark));
        setSelectable(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        cbSelection = new javax.swing.JCheckBox();
        nameLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        setMinimumSize(new java.awt.Dimension(250, 25));
        setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        iconLabel.setPreferredSize(new java.awt.Dimension(21, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(iconLabel, gridBagConstraints);

        cbSelection.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(cbSelection, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(nameLabel, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.WEST);

    }//GEN-END:initComponents
    public void setName(String namex){
        name = namex;
    }
    
    public String getName(){
        return name;
    }
    
    public void setInstallerName(String namex){
        installerName = namex;
    }
    
    public String getInstallerName(){
        return installerName;
    }
    
    public void setDisplayName(String namex){
        nameLabel.setText(namex);
        displayName = namex;
    }
    
    public String getDisplayName(){
        return displayName;
    }
    
    public void setDesription(String descriptionx){
        description = descriptionx;
    }
    
    public String getDesription(){
        return description;
    }
    
    public void setActive(boolean activex){
        active = activex;
        //setSelected(activex);
    }
    
    public void addItemListener(ItemListener listener){
        cbSelection.addItemListener(listener);
    }
    
    public boolean getActive(){
        return active;
    }
    
    public void setRequired(boolean reqx){
        required = reqx;
        setSelectable(false);
    }
    
    public boolean getRequired(){
        return required;
    }
    
    public void setSelectable(boolean selectable){
        if(getRequired()) selectable=false;
        if(selectable){
            iconLabel.setVisible(false);
            cbSelection.setVisible(true);
        } else {
            iconLabel.setVisible(true);
            cbSelection.setVisible(false);
        }
    }
    
    public void setRequiredComponent(ComponentDescriptor required){
        //System.out.println(required.getName());
        requiredComponent = required;
        requiredComponent.setRequiredByComponent(this);
        if(getActive()) requiredComponent.setSelectable(false);
    }
    
    public ComponentDescriptor getRequiredComponent(){
        return requiredComponent;
    }
    
    public void setRequiredByComponent(ComponentDescriptor requiredBy){
        requiredByComponent = requiredBy;
    }
    
    public ComponentDescriptor getRequiredByComponent(){
        return requiredByComponent;
    }
    
    public void enableRequiredComponent(boolean enable){
        if(requiredComponent != null){
            requiredComponent.setSelectable(enable);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox cbSelection;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
    
}
