// ComponentSelectionPanel.java
// Author  Winston Prakash


package com.nayaware.netinstaller;

import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.awt.event.*;

public class ComponentSelectionPanel extends WizardPanel implements ItemListener{
    String descriptionText="Select the components of Forte for Java you wish to install. The components(s) required either by Forte for Java core or other selected components(s) cannot be unselected";
    String componentDescription="";
    
    /** Creates new form ComponentSelectionPanel */
    public ComponentSelectionPanel() {
        initComponents();
    }
    
    public void displayPanel(){
        componentPanel.removeAll();        
        for(int i=0;i<SoftwareObjects.getSize();i++){
            addComponent(SoftwareObjects.getObject(i),i);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        descTextArea = new javax.swing.JTextArea();
        componentTextArea = new javax.swing.JTextArea();
        componentPanelContainer = new javax.swing.JPanel();
        componentPanel = new javax.swing.JPanel();

        descTextArea.setBackground(new java.awt.Color(204, 204, 204));
        descTextArea.setLineWrap(true);
        descTextArea.setRows(3);
        descTextArea.setText(descriptionText);
        descTextArea.setWrapStyleWord(true);
        descTextArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        add(descTextArea, java.awt.BorderLayout.NORTH);

        componentTextArea.setBackground(new java.awt.Color(204, 204, 204));
        componentTextArea.setRows(4);
        componentTextArea.setText(componentDescription);
        componentTextArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        add(componentTextArea, java.awt.BorderLayout.SOUTH);

        componentPanelContainer.setLayout(new java.awt.BorderLayout());

        componentPanel.setLayout(new java.awt.GridBagLayout());

        componentPanelContainer.add(componentPanel, java.awt.BorderLayout.NORTH);

        add(componentPanelContainer, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    public void addComponent(ComponentDescriptor comp,int index){
        //System.out.println("Adding Component :" + comp.getName());        
        comp.addItemListener(this);
        java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = index;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        componentPanel.add(comp, gridBagConstraints);
    }
    
    public void itemStateChanged(java.awt.event.ItemEvent itemEvent){
        JCheckBox cbSelected = (JCheckBox) itemEvent.getItemSelectable();
        Container comp = cbSelected.getParent();
        while (!(comp instanceof ComponentDescriptor)){
            comp = comp.getParent();
        }
        ComponentDescriptor compSelected = (ComponentDescriptor) comp;
        if (itemEvent.getStateChange() == ItemEvent.DESELECTED){
            compSelected.enableRequiredComponent(true);
            compSelected.setActive(false);
        } else {
            compSelected.enableRequiredComponent(false);
            compSelected.setActive(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel componentPanelContainer;
    private javax.swing.JTextArea componentTextArea;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JPanel componentPanel;
    // End of variables declaration//GEN-END:variables
    
}
