// EditionSelectionPanel.java
// Author  Winston Prakash

package com.nayaware.netinstaller;

public class EditionSelectionPanel extends WizardPanel {
    
    String editionMsg = "Selection the edition you want to install.";
    String ceEdition = "Community Edition";
    String eeEdition = "Enterprise Edition";
    String meEdition = "Mobile Edition";
    
    String ceText = "The Community Edition software is offered at NO CHARGE and includes a complete and highly-integrated set of tools for teams of developers building database-aware Web applications -- including a Web browser, a Web server, and a relational database. Developers can build stand-alone applications, applets, and JavaBeans[tm].";
    String eeText = "The Enterprise Edition software is ideally suited for developing scalable robust applications and services based on the Java 2 Enterprise Edition (J2EE[tm]) architecture. It enables developers to build and assemble Enterprise JavaBeans[tm] (EJB[tm]) into an application that can be deployed to integrated application servers, such as the iPlanet[tm] Application Server.";
    String meText = "The Mobile Edition software is offered at NO CHARGE and includes a complete and highly-integrated set of tools for developing scalable Wireless applications and based on the Java 2 Mobile Edition (J2ME[tm]) architecture.";
    
    
    /** Creates new form EditionSelectionPanel */
    public EditionSelectionPanel() {
        initComponents();
        ceEditionRadioButton.setSelected(true);
        editionDescTextArea.setText(ceText);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        editionButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        editionSelectionPanel = new javax.swing.JPanel();
        descTextArea = new javax.swing.JTextArea();
        editionPanel = new javax.swing.JPanel();
        ceEditionRadioButton = new javax.swing.JRadioButton();
        eeEditionRadioButton = new javax.swing.JRadioButton();
        meEditionRadioButton = new javax.swing.JRadioButton();
        editionDescPanel = new javax.swing.JPanel();
        editionDescTextArea = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(450, 350));
        editionSelectionPanel.setLayout(new java.awt.BorderLayout());

        editionSelectionPanel.setPreferredSize(new java.awt.Dimension(400, 200));
        descTextArea.setBackground(new java.awt.Color(204, 204, 204));
        descTextArea.setFont(new java.awt.Font("Times New Roman", 1, 14));
        descTextArea.setLineWrap(true);
        descTextArea.setText(editionMsg);
        descTextArea.setWrapStyleWord(true);
        descTextArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        descTextArea.setPreferredSize(new java.awt.Dimension(450, 50));
        editionSelectionPanel.add(descTextArea, java.awt.BorderLayout.NORTH);

        editionPanel.setLayout(new java.awt.GridBagLayout());

        editionPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        editionPanel.setPreferredSize(new java.awt.Dimension(350, 100));
        ceEditionRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        ceEditionRadioButton.setText(ceEdition);
        editionButtonGroup.add(ceEditionRadioButton);
        ceEditionRadioButton.setMinimumSize(new java.awt.Dimension(98, 40));
        ceEditionRadioButton.setPreferredSize(new java.awt.Dimension(350, 40));
        ceEditionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceEditionRadioButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editionPanel.add(ceEditionRadioButton, gridBagConstraints);

        eeEditionRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        eeEditionRadioButton.setText(eeEdition);
        editionButtonGroup.add(eeEditionRadioButton);
        eeEditionRadioButton.setMinimumSize(new java.awt.Dimension(98, 40));
        eeEditionRadioButton.setPreferredSize(new java.awt.Dimension(350, 40));
        eeEditionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeEditionRadioButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editionPanel.add(eeEditionRadioButton, gridBagConstraints);

        meEditionRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        meEditionRadioButton.setText(meEdition);
        editionButtonGroup.add(meEditionRadioButton);
        meEditionRadioButton.setMinimumSize(new java.awt.Dimension(100, 40));
        meEditionRadioButton.setPreferredSize(new java.awt.Dimension(350, 40));
        meEditionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meEditionRadioButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editionPanel.add(meEditionRadioButton, gridBagConstraints);

        editionSelectionPanel.add(editionPanel, java.awt.BorderLayout.CENTER);

        add(editionSelectionPanel, java.awt.BorderLayout.NORTH);

        editionDescPanel.setLayout(new java.awt.BorderLayout());

        editionDescPanel.setMinimumSize(new java.awt.Dimension(450, 100));
        editionDescPanel.setPreferredSize(new java.awt.Dimension(450, 100));
        editionDescTextArea.setBackground(new java.awt.Color(204, 204, 204));
        editionDescTextArea.setColumns(40);
        editionDescTextArea.setEditable(false);
        editionDescTextArea.setFont(new java.awt.Font("Serif", 0, 14));
        editionDescTextArea.setLineWrap(true);
        editionDescTextArea.setRows(7);
        editionDescTextArea.setWrapStyleWord(true);
        editionDescTextArea.setMargin(new java.awt.Insets(5, 5, 5, 5));
        editionDescPanel.add(editionDescTextArea, java.awt.BorderLayout.CENTER);

        add(editionDescPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    private void meEditionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meEditionRadioButtonActionPerformed
        SoftwareObjects.setEdition("me");
        editionDescTextArea.setText(meText);
        //System.out.println("Edition Selected: " + SoftwareObjects.getEdition());
    }//GEN-LAST:event_meEditionRadioButtonActionPerformed
    
    private void eeEditionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeEditionRadioButtonActionPerformed
        SoftwareObjects.setEdition("ee");
        editionDescTextArea.setText(eeText);
        //System.out.println("Edition Selected: " + SoftwareObjects.getEdition());
    }//GEN-LAST:event_eeEditionRadioButtonActionPerformed
    
    private void ceEditionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceEditionRadioButtonActionPerformed
        SoftwareObjects.setEdition("ce");
        editionDescTextArea.setText(ceText);
        //System.out.println("Edition Selected: " + SoftwareObjects.getEdition());
    }//GEN-LAST:event_ceEditionRadioButtonActionPerformed
    
    public boolean queryExit(){
        SoftwareObjects.setObjectList();
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel editionSelectionPanel;
    private javax.swing.JRadioButton ceEditionRadioButton;
    private javax.swing.JRadioButton eeEditionRadioButton;
    private javax.swing.JTextArea editionDescTextArea;
    private javax.swing.JRadioButton meEditionRadioButton;
    private javax.swing.JPanel editionPanel;
    private javax.swing.JPanel editionDescPanel;
    private javax.swing.ButtonGroup editionButtonGroup;
    private javax.swing.JTextArea descTextArea;
    // End of variables declaration//GEN-END:variables
    
}
