// InstallPanel.java
// Author Winston Prakash

package com.nayaware.netinstaller;

import java.net.*;
import java.io.*;
import java.util.*;
import javax.swing.*;

public class LicensePanel extends WizardPanel {
    
    String descriptionText="Please read the following Binary Code License carefully";
    String agreeButtonText="Yes. I agree to the license terms";
    String notAgreeButtonText="No. I donot agree to the license terms";
    
    String ceLicenseFile = "licenseCE.html";
    String eeLicenseFile = "licenseEE.html";
    String meLicenseFile = "licenseME.html";
    String licenseFile = ceLicenseFile;
    
    private boolean agree = false;
    
    public LicensePanel() {
        initComponents();
    }
    
    public void displayPanel(){
        if(SoftwareObjects.getEdition().equals("ce")) licenseFile = ceLicenseFile;
        if(SoftwareObjects.getEdition().equals("ee")) licenseFile = eeLicenseFile;
        if(SoftwareObjects.getEdition().equals("me")) licenseFile = meLicenseFile;
        URL htmlURL = getClass().getClassLoader().getResource("com/nayaware/netinstaller/resources/"+ licenseFile);
        JEditorPane editorPane = new JEditorPane();
        editorPane.setEditable(false);
        try {
            editorPane.setPage(htmlURL);
        } catch (IOException e) {
            System.err.println("Attempted to read a bad URL: " + htmlURL);
        }
        licenseTextScrollPane.setViewportView(editorPane);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        approvalButtonGroup = new javax.swing.ButtonGroup();
        descTextArea = new javax.swing.JTextArea();
        componentPanel = new javax.swing.JPanel();
        licenseTextScrollPane = new javax.swing.JScrollPane();
        approvePanel = new javax.swing.JPanel();
        agreeButton = new javax.swing.JRadioButton();
        notAgreeButton = new javax.swing.JRadioButton();

        descTextArea.setBackground(new java.awt.Color(204, 204, 204));
        descTextArea.setText(descriptionText);
        descTextArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        add(descTextArea, java.awt.BorderLayout.NORTH);

        componentPanel.setLayout(new java.awt.BorderLayout());

        componentPanel.setPreferredSize(new java.awt.Dimension(450, 250));
        licenseTextScrollPane.setMinimumSize(new java.awt.Dimension(425, 250));
        licenseTextScrollPane.setPreferredSize(new java.awt.Dimension(425, 250));
        componentPanel.add(licenseTextScrollPane, java.awt.BorderLayout.CENTER);

        add(componentPanel, java.awt.BorderLayout.CENTER);

        approvePanel.setLayout(new java.awt.GridLayout(2, 0));

        approvePanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 10, 10, 1)));
        approvePanel.setPreferredSize(new java.awt.Dimension(450, 50));
        agreeButton.setText(agreeButtonText);
        approvalButtonGroup.add(agreeButton);
        agreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeButtonActionPerformed(evt);
            }
        });

        approvePanel.add(agreeButton);

        notAgreeButton.setSelected(true);
        notAgreeButton.setText(notAgreeButtonText);
        approvalButtonGroup.add(notAgreeButton);
        notAgreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notAgreeButtonActionPerformed(evt);
            }
        });

        approvePanel.add(notAgreeButton);

        add(approvePanel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void notAgreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notAgreeButtonActionPerformed
        agree = false;
    }//GEN-LAST:event_notAgreeButtonActionPerformed
    
    private void agreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeButtonActionPerformed
        agree = true;
    }//GEN-LAST:event_agreeButtonActionPerformed
    
    public boolean queryExit(){
        if(!agree){
            String message ="You have not agreed to the Binary Code License.\n Select the agree button or press cancel to exit";
            String title = "Binary Code License Agreement";
            JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agreeButton;
    private javax.swing.JPanel approvePanel;
    private javax.swing.JRadioButton notAgreeButton;
    private javax.swing.ButtonGroup approvalButtonGroup;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JPanel componentPanel;
    private javax.swing.JScrollPane licenseTextScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
