// PreInstallSummaryPanel.java
// Author  Winston Prakash
 
package com.nayaware.netinstaller;

import javax.swing.*;
 
public class PreInstallSummaryPanel extends WizardPanel {
    String descriptionText="The following components of Forte for Java will be installed on your machine. Click next to Install";
    String componentDescription="";   
 
    public PreInstallSummaryPanel() {
        initComponents();
    }
    
    public void displayPanel(){
        componentPanel.removeAll();        
        for(int i=0;i<SoftwareObjects.getSize();i++){
            addComponent(SoftwareObjects.getObject(i));
        }
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        descTextArea = new javax.swing.JTextArea();
        componentTextArea = new javax.swing.JTextArea();
        componentPanelContainer = new javax.swing.JPanel();
        componentPanel = new javax.swing.JPanel();

        descTextArea.setBackground(new java.awt.Color(204, 204, 204));
        descTextArea.setEditable(false);
        descTextArea.setLineWrap(true);
        descTextArea.setRows(3);
        descTextArea.setText(descriptionText);
        descTextArea.setWrapStyleWord(true);
        descTextArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        add(descTextArea, java.awt.BorderLayout.NORTH);

        componentTextArea.setBackground(new java.awt.Color(204, 204, 204));
        componentTextArea.setEditable(false);
        componentTextArea.setRows(4);
        componentTextArea.setText(componentDescription);
        componentTextArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        add(componentTextArea, java.awt.BorderLayout.SOUTH);

        componentPanelContainer.setLayout(new java.awt.BorderLayout());

        componentPanel.setLayout(new java.awt.GridBagLayout());

        componentPanelContainer.add(componentPanel, java.awt.BorderLayout.NORTH);

        add(componentPanelContainer, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public void addComponent(ComponentDescriptor comp){
        if(!comp.getActive()) return;
        java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        //gridBagConstraints.gridy = ;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        JLabel compLabel = new JLabel();
        compLabel.setText(comp.getDisplayName());
        compLabel.setMinimumSize(new java.awt.Dimension(200, 24));
        compLabel.setPreferredSize(new java.awt.Dimension(300, 24));  
        componentPanel.add(compLabel, gridBagConstraints);
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel componentPanelContainer;
    private javax.swing.JTextArea componentTextArea;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JPanel componentPanel;
    // End of variables declaration//GEN-END:variables
    
}
