// WelcomePanel.java
// Author  Winston Prakash 

package com.nayaware.netinstaller;

public class WelcomePanel extends WizardPanel {
    
    String welcomeText = "Welcome to the <Your Product> installation wizard.";
    String infoText = "This installation wizard will install the following <Your Product> on your computer";
    String productName = "<Your Product>";
    String copyRightText = "Copyright <Your Company>, Inc. All rights reserved."; 
    String licenseTermText = "Use is subject to license terms.";
    
    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        initComponents();
    }
    
    public void displayPanel(){
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        descriptionTextArea = new javax.swing.JTextArea();
        infoTextArea = new javax.swing.JTextArea();
        productNameTextArea = new javax.swing.JTextArea();
        copyRightTextArea = new javax.swing.JTextArea();
        licenseTermTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(450, 350));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        descriptionTextArea.setBackground(new java.awt.Color(204, 204, 204));
        descriptionTextArea.setEditable(false);
        descriptionTextArea.setFont(new java.awt.Font("Times New Roman", 1, 14));
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(2);
        descriptionTextArea.setText(welcomeText
        );
        descriptionTextArea.setWrapStyleWord(true);
        descriptionTextArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        descriptionTextArea.setPreferredSize(new java.awt.Dimension(450, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(descriptionTextArea, gridBagConstraints);

        infoTextArea.setBackground(new java.awt.Color(204, 204, 204));
        infoTextArea.setEditable(false);
        infoTextArea.setFont(new java.awt.Font("Times New Roman", 0, 14));
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(2);
        infoTextArea.setText(infoText);
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(infoTextArea, gridBagConstraints);

        productNameTextArea.setBackground(new java.awt.Color(204, 204, 204));
        productNameTextArea.setEditable(false);
        productNameTextArea.setFont(new java.awt.Font("Times New Roman", 3, 14));
        productNameTextArea.setText(productName);
        productNameTextArea.setMargin(new java.awt.Insets(20, 20, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(productNameTextArea, gridBagConstraints);

        copyRightTextArea.setBackground(new java.awt.Color(204, 204, 204));
        copyRightTextArea.setEditable(false);
        copyRightTextArea.setText(copyRightText);
        copyRightTextArea.setMargin(new java.awt.Insets(5, 20, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(copyRightTextArea, gridBagConstraints);

        licenseTermTextArea.setBackground(new java.awt.Color(204, 204, 204));
        licenseTermTextArea.setEditable(false);
        licenseTermTextArea.setText(licenseTermText);
        licenseTermTextArea.setMargin(new java.awt.Insets(0, 20, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(licenseTermTextArea, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JTextArea copyRightTextArea;
    private javax.swing.JTextArea productNameTextArea;
    private javax.swing.JTextArea licenseTermTextArea;
    // End of variables declaration//GEN-END:variables
    
}
